name: 🐛 バグ報告
description: バグの報告
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 バグ報告テンプレート
        
        バグの詳細情報をお教えください。

  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 バグの説明
      description: 何が起こっているかを簡潔に説明してください
      placeholder: 支出を記録しようとすると、アプリがクラッシュする
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 再現手順
      description: バグを再現するための手順
      placeholder: |
        1. ダッシュボードページにアクセス
        2. "新しい支出を記録"ボタンをクリック
        3. 金額に"1000"を入力
        4. "保存"ボタンをクリック
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ 期待される動作
      description: 本来どのような動作をするべきか
      placeholder: 支出が正常に記録され、ダッシュボードに反映される
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ 実際の動作
      description: 実際に何が起こるか
      placeholder: エラーメッセージが表示され、データが保存されない
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 環境情報
      description: OS、ブラウザ、バージョンなど
      placeholder: |
        - OS: macOS 14.0
        - ブラウザ: Chrome 120.0
        - デバイス: MacBook Pro
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 追加情報
      description: スクリーンショット、ログ、その他の関連情報
      placeholder: |
        - スクリーンショット: [添付]
        - コンソールエラー: [ログ]
        - 関連Issue: #123
    validations:
      required: false 